### ISSUE TITLE
Map User Attributes

### ISSUE THREAD

**Issue by drouillard** [shrinedev/loopback-extensions#1]
We want a way to map attributes from the access token to the user object returned to Applications that use the Keycloak Gate.

I left my comments on the initial code.

https://github.com/shrinedev/loopback-extensions/commit/b456c448ebb561fe8cd3ab1ede0faf2db789373a

I don't think we want to allow for arbitrary mappings. The way to do this would be an ENUM type construct that can be overridden by applications that use the Keycloak Gate

**Comment by drouillard** [comment]
@chadmg can we close this?

**Comment by chadmg** [comment]
@drouillard Yup, closed.
